name: Rust
run-name: Rust
on: [push, pull_request]

jobs:
    cache:
      runs-on: ubuntu-latest
      steps:
      - name: Temporarily modify the rust toolchain version
        run: rustup override set nightly
      - name: Output rust version for educational purposes
        run: rustup --version
            
      - name: Cache
        uses: actions/cache@v4
        with:
            path: |
                ~/.cargo/registry
                ~/.cargo/git
                target
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    fmt:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v6
      - name: Format
        run: cargo fmt --all -- --check
    
    clippy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v6
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings        
    
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            BUILD_TARGET: [release] # refers to a cargo profile
      outputs:
        release_built: ${{ steps.set-output.outputs.release_built }}
      steps:
        - uses: actions/checkout@v6
        - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
          run: cargo test --profile ${{ matrix.BUILD_TARGET }}
